source "https://rubygems.org"

gem "jekyll", "4.2.0"
gem "just-the-docs"

gem "webrick" # required for ruby 3.0+
# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]