name: Automate
on:
  repository_dispatch:
    types: [auto]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Automation here
        run: |
          echo "Call a script to do something .."
          echo "Name     = " ${{ toJson(github.event.client_payload.name) }}
          echo "Password = " ${{ toJson(github.event.client_payload.password) }}
