name: SETUP
on:
  workflow_dispatch:
    inputs:
      domain:
        default: 'testspace'
        description: 'Defaults to testspace.com'
      org:
        description: 'Defaults to gh org name, leave this blank for most cases'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup client using Passed org
        if: github.event.inputs.org  != ''
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.event.inputs.org }}.${{ github.event.inputs.domain }}.com
      - name: Setup client using GitHub org 
        if: github.event.inputs.org  == ''
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}.${{ github.event.inputs.domain }}.com
      - name: Setup failure tracking
        run: |
          ./push.setup.sh